# Site settings
title: The OpenType Cookbook
email: tal@typesupply.com
description: > # this means to ignore newlines until "baseurl:"
  An introduction to OpenType features for type designers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://opentypecookbook.com" # the base hostname & protocol for your site

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title/


gems:
  - rouge
# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME